name: Client

on:
  push:
    branches: 
      - '*.*.*/main'
    paths:
      - '.github/workflows/client.yml'
      - 'client/**'
      - '!client/public/**'
  pull_request:
    branches: 
      - '*.*.*/main'
    paths:
      - '.github/workflows/client.yml'
      - 'client/**'
      - '!client/public/**'
      - '!client/src/resources/**'

jobs:
  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci --force
      - run: npm run build --if-present
      - run: npm test --passWithNoTests
