name: Deploy (Dev)

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: deploy-dev
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JP_SERVER_HOSTNAME }}
          username: ${{ secrets.JP_SERVER_USER }}
          password: ${{ secrets.JP_SERVER_PASSWORD }}
          script: |
            cd /mafia-app/dev
            ./update.sh
