name: Server

on:
  push:
    branches: 
      - '*.*.*/main'
    paths:
      - '.github/workflows/server.yml'
      - 'server/**'
      - '!server/resources/**'
  pull_request:
    branches: 
      - '*.*.*/main'
    paths:
      - '.github/workflows/server.yml'
      - 'server/**'
      - '!server/resources/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd server && cargo build --verbose
